language: python
sudo: false
dist: trusty

addons:
  mariadb: '10.1'
  hosts:
    - database

python:
  - '3.4'
  - '3.5'

install:
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS zoomtest;'
  - mysql -uroot -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL ON zoomtest.* TO 'testuser'@'localhost';"
  - mysql -uroot zoomtest < tools/zoom/sql/setup_mysql.sql
script:
  - nosetests --with-coverage --cover-package=zoom --with-doctest -v ./zoom/* ./tests/unittests/*

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coveralls; fi

notifications:
  email:
    recipients:
      - support@dynamic-solutions.com
    on_success: never
    on_failure: always
  slack:
    secure: PntV1OHhuzM9Dl5/G41oeNvngqnSYD19j4Tm0bXOMg4bNklCB3A/E3vHiwpN4pgn8jNoAmlixEgMO/aDTBxCi0kRsCYdaGRN6omQ7YJbqZazbQC7klxQhKkmtI86S02vfKixtg/X1qtFL7hVJ5ob37UThSQqfGI7A6LPXJlZueVcNwuFDh8OYuS6w1txmDcZQ2nRLliRlspgd7w1hq8m81attXgyZG9MSCPTCBULTNQVGHTtj3u/smsqxcYi+4XSgKwPg3xLxGX5ZuZk0to2nljbUIiTjS5uuTIU03/8SNbltrDM5+NVMxVICMNbUR9RpQo30vvoMbubA5bEqXQe6znbv1K74v9+U4WY7WpOWaJLdwUVwfmbzvWSkfIff/Mis+1Hau+Yz+VdKx1AEalO5JndRgaXobJWIzeKHY8TkpRwAbcMbz61lxJ4boauQwZkLOq9hn1XkunZ/m7GlFCaTW3vSrQfm9rems2fE3EwA9bdgkgAFWRgCzYbTc3fErL9jXXVhXNUDT0rsftwuCC4I2hGo+no27CCNCLIqcj1k0kfN34EeJ9R2UbQOf1O1eGgARFS5gRbp9ozpEz2YZ6N2Qu2cp65Z7IgRZWEPB7AWHwZekh7h0ThRoy639dn7t+1fy0eRiZuOaQD0SKT5WgZl0XpfxfzXqFWYkAKE0EeJSw=
    on_success: always
    on_failure: always
