language: python
sudo: false
dist: trusty

addons:
  mariadb: '10.1'
  hosts:
    - database

python:
  - "3.4"
  - "3.5"

install:
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS zoomtest;'
  - mysql -uroot -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL ON zoomtest.* TO 'testuser'@'localhost';"
  - mysql -uroot zoomtest < tools/zoom/sql/setup_mysql.sql
script:
  - nosetests --with-coverage --cover-package=zoom --with-doctest -v ./zoom/* ./tests/unittests/*

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
          coveralls;
      fi

notifications:
  email:
    recipients:
      - support@dynamic-solutions.com
    on_success: never
    on_failure: always
  slack:
    secure: GFwIeZTnDI2oni2oQfUvYf3q66gYjs8JE4CGQcpge8sDLPGlZ2fCDuMijIG2IrW3rNqd8RtXf8ERjfpibpyn/7vXQe1rgJ9nMVdGhDPycrc03RC9Alp5+kbmusa/6kSxtvmj6h+LsADUULjVpHc4MBqyPpT6+URQ1N0T89x9S7TCGFVceR3eudyphxcyazpVqQB7F7fyJnS7zwbySoatRUA8U7mQ1jKnIfO9bYov+HvF5lfzeN+sNk/w9kicGv3/SoXLrUS2ODCF/XmIVUHLWE9L34oKex26OruSWII5H7/1n2WnRczce+DxHfzj/udIXRApmFzLYqz9Rza+Q5AVQcCK3kjFgMhEnqOpDBszsyaP8lokJhie18bgus5tMCkUd6GY00OsXYumbjNfM7FuJACPpLtI+CKrVuw6OSc5rDQkYQuqBXk6pAA5UBnk8por/FBp2UY0RNDQlsOSGU/U4xyPjYYmm/rHtw9yB3WICMH7rWNgz/2Nj4+egJdV+fDz/Fc9XuDI4tLAlMo9TgACzVKprToTBZoORL6f1PC9jCYJlVpapnAnOY34Mo3cYiG30nmfYheEifQMj1jjmKpuMD1nPsUIaHF1oDAxFsQkZlTTBIfW4zILK5W+flwMN9D6LhOBHrn9fVL4kxMTr/Hi+HR/hOF2tdbAuAI9H2nyJE4=
    on_success: always
    on_failure: always
